In [5]:
from sklearn.linear_model import Perceptron

X = [[0,0], [0,1], [1,0], [1,1]]
y = [-1, 1, 1, 1]

p = Perceptron()
p.fit(X, y)

print('학습된 퍼셉트론의 매개변수: ', p.coef_, p.intercept_)
print('훈련집합에 대한 예측: ', p.predict(X))
print('정확률 측정 : ', p.score(X, y) * 100, "%")

학습된 퍼셉트론의 매개변수:  [[2. 2.]] [-1.]
훈련집합에 대한 예측:  [-1  1  1  1]
정확률 측정 :  100.0 %


## 필기 숫자 데이터 인식

In [7]:
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
import numpy as np

#데이터셋 읽고 분할
digit = datasets.load_digits()
X_train, X_test, y_train, y_test = train_test_split(digit.data, digit.target, train_size=0.6)

#fit 으로 학습
p = Perceptron(max_iter=100, eta0=0.001, verbose=0)
p.fit(X_train, y_train)

res = p.predict(X_test)

#혼동 행렬
conf = np.zeros((10, 10))

for i in range(len(res)):
    conf[res[i]][y_test[i]] += 1
print(conf)

#정확률 계산
no_correct = 0
for i in range(10):
    no_correct += conf[i][i]
accuracy = no_correct/len(res)

print("\n테스트 집합에 대한 정확률은 ", accuracy*100, '%입니다.')

[[71.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 54.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 74.  0.  0.  0.  0.  0.  2.  0.]
 [ 0.  0.  1. 65.  0.  1.  0.  0.  4.  2.]
 [ 2.  2.  0.  0. 75.  1.  0.  0.  0.  0.]
 [ 2.  1.  0.  0.  0. 79.  0.  0.  2.  2.]
 [ 0.  1.  0.  0.  0.  1. 77.  0.  3.  0.]
 [ 0.  0.  0.  0.  1.  0.  0. 64.  3.  1.]
 [ 0.  9.  0.  0.  2.  0.  2.  1. 59.  4.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. 51.]]

테스트 집합에 대한 정확률은  93.04589707927677 %입니다.


##### 퍼셉트론의 한계
선형분리가 안되는 데이터에서는 높은 오류율
다층 퍼셉트론으로 비선형 확장이 필요함

##### 다층 퍼셉트론의 구조
입력층, 은닉층, 출력층으로 구성
