



# 기계학습 10주차 실습 자료
#### 조교 : 김도경




#1. sklean이란?
- Scikit-learn
- 머신러닝에 사용되는 지도/비지도 학습 알고리즘을 제공하는 파이썬 라이브러리
- Google Summer of Code 프로젝트로 2007년 시작 ~ January 2021. scikit-learn 0.24.1 버전까지 제공
- https://scikit-learn.org/stable/
- 이용 가이드
  - https://scikit-learn.org/stable/user_guide.html
- 예제
  - https://scikit-learn.org/stable/auto_examples/index.html
- gihub 
  - https://github.com/scikit-learn/scikit-learn



# 2. OR 데이터 인식
- OR 데이터에 퍼셉트론 적용

In [1]:
from sklearn.linear_model import Perceptron

# 훈련 집합 구축

X = [[0,0],[0,1],[1,0],[1,1]]
y = [-1,1,1,1]
11
# fit 함수로 Perceptron 학습

p = Perceptron()
p.fit(X,y)

print('학습된 퍼셉트론의 매개변수: ', p.coef_,p.intercept_)
print('훈련집합에 대한 예측: ', p.predict(X))
print('정확률 측정: ', p.score(X,y)*100, "%")

학습된 퍼셉트론의 매개변수:  [[2. 2.]] [-1.]
훈련집합에 대한 예측:  [-1  1  1  1]
정확률 측정:  100.0 %


# 3. 필기 숫자 데이터 인식
## 3-1. sklearn이 제공하는 숫자 데이터에 퍼셉트론 적용
- Perceptron 파라메터 
  - max_iter : int, default=1000

    The maximum number of passes over the training data (aka epochs).
    It only impacts the behavior in the fit method, and not the
    partial_fit method.
  - verbose : int, default=0

    The verbosity level

  - eta0 : double, default=1

    Constant by which the updates are multiplied.

- 정확도 = 예측값결과와 실제값이 동일한 건수 / 전체 데이터수 

In [2]:
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
import numpy as np

# 데이터셋을 읽고 훈련 집합과 테스트 집합으로 분할
digit = datasets.load_digits()
x_train, x_test, y_train, y_test = train_test_split(digit.data, digit.target, train_size = 0.6)

# fit 함수로 Perceptron 학습
p = Perceptron(max_iter = 100, eta0 = 0.001, verbose = 0) # 모델 객체 생성
p.fit(x_train, y_train) # digit 데이터로 모델링 (모델 학습)

res = p.predict(x_test) # 테스트 집합으로 예측 

# 혼동 행렬 
conf = np.zeros((10,10))

for i in range(len(res)):
  conf[res[i]][y_test[i]] += 1
print(conf)

# 정확률 계산
no_correct = 0
for i in range(10):
  no_correct += conf[i][i]
accuracy = no_correct/len(res)
print('\n테스트 집합에 대한 정확률은 ', accuracy*100,"%입니다.")

[[76.  0.  0.  0.  0.  0.  1.  0.  1.  0.]
 [ 0. 53.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  2. 69.  0.  0.  0.  0.  0.  0.  2.]
 [ 0.  2.  1. 74.  0.  0.  0.  0.  0.  0.]
 [ 0.  3.  0.  0. 65.  0.  2.  1.  0.  0.]
 [ 0.  0.  0.  2.  0. 68.  0.  0.  0.  1.]
 [ 0.  2.  0.  0.  0.  1. 70.  0.  0.  0.]
 [ 0.  0.  0.  2.  0.  1.  0. 66.  0.  0.]
 [ 0. 13.  1.  2.  1.  0.  0.  1. 66.  3.]
 [ 0.  4.  0.  1.  0.  2.  0.  0.  0. 60.]]

테스트 집합에 대한 정확률은  92.76773296244785 %입니다.


# 퍼셉트론의 한계

- 선형 분리가 불가능한 데이터에서는 높은 오류율을 보인다
- 은닉층을 추가한 다층 퍼셉트론으로 비선형 확장이 필요하다
  - 퍼셉트론을 하나 더쓰면 XOR 문제를 풀 수 있다

# 다층 퍼셉트론의 구조 

- 입력층, 은닉층, 출력층으로 구성 
  - 층을 연결하는 가중치 뭉치가 두개 있어 3층이 아닌 2층 신경망으로 간주됨

## 3-2. sklearn이 제공하는 숫자 데이터에 다층 퍼셉트론 적용

- 하이퍼 매개변수란 ?
  - 모델의 구조와 모델의 학습 과정을 제어하는 역할 
---

- MLPClassifier 함수의 하이퍼 매개변수
  - hidden_layer_sizes = (100)
    - 100개 노드를 가진 은닉층 한개를 둠 
    - 100개와 80개 노드를 가진 은닉층 두개를 설정하려면 hidden_layer_sizes=(100,80)
  - learning_rate_init = 0.001
    - learning_rate를 0.00로 설정 
  - batch_size = 32
    - 미니 배치 크기를 32로 설정
  - max_iter = 300
    - 최대 반복을 300으로 설정
  - solver = 'sgd'
    - 최적화 알고리즘으로 스토캐스틱 경사 알고리즘을 사용
  - verbose = True

In [3]:
from sklearn import datasets
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
import numpy as np

# 데이터셋을 읽고 훈련 집합과 테스트 집합으로 분할
digit = datasets.load_digits()
x_train, x_test, y_train, y_test = train_test_split(digit.data, digit.target, train_size = 0.6)

# MLP 분류기 모델을 학습
mlp = MLPClassifier(hidden_layer_sizes = (100), learning_rate_init = 0.001, batch_size = 32, max_iter = 300, solver = 'sgd', verbose = True) # 모델 객체 생성
mlp.fit(x_train, y_train) # digit 데이터로 모델링 (모델 학습)

res = mlp.predict(x_test) # 테스트 집합으로 예측 

# 혼동 행렬 
conf = np.zeros((10,10))

for i in range(len(res)):
  conf[res[i]][y_test[i]] += 1
print(conf)

# 정확률 계산
no_correct = 0
for i in range(10):
  no_correct += conf[i][i]
accuracy = no_correct/len(res)
print('\n테스트 집합에 대한 정확률은 ', accuracy*100,"%입니다.")

Iteration 1, loss = 2.32419751
Iteration 2, loss = 0.31923012
Iteration 3, loss = 0.20926782
Iteration 4, loss = 0.16324749
Iteration 5, loss = 0.12806690
Iteration 6, loss = 0.10703706
Iteration 7, loss = 0.09491709
Iteration 8, loss = 0.08168506
Iteration 9, loss = 0.07534916
Iteration 10, loss = 0.06549842
Iteration 11, loss = 0.06099887
Iteration 12, loss = 0.05517300
Iteration 13, loss = 0.05182664
Iteration 14, loss = 0.04699411
Iteration 15, loss = 0.04274841
Iteration 16, loss = 0.04004611
Iteration 17, loss = 0.03772022
Iteration 18, loss = 0.03445131
Iteration 19, loss = 0.03165312
Iteration 20, loss = 0.03143489
Iteration 21, loss = 0.02900459
Iteration 22, loss = 0.02774230
Iteration 23, loss = 0.02599011
Iteration 24, loss = 0.02478012
Iteration 25, loss = 0.02374583
Iteration 26, loss = 0.02220715
Iteration 27, loss = 0.02179454
Iteration 28, loss = 0.02088197
Iteration 29, loss = 0.02053743
Iteration 30, loss = 0.01946761
Iteration 31, loss = 0.01874325
Iteration 32, los

# 4. MNIST 데이터셋으로 확장하기
- MNIST 필기 숫자 데이터셋
  - 훈련 집합 60000자 + 테스트 집합 10000자
  - 샘플은 28*28 맵으로 표현 

In [4]:
from sklearn.datasets import fetch_openml
from sklearn.neural_network import MLPClassifier
import matplotlib.pyplot as plt
import numpy as np

# MNIST 데이터셋을 읽고 훈련 집합과 테스트 집합으로 분할
mnist = fetch_openml('mnist_784')
mnist.data = mnist.data/255.0 # [0,255] 범위를 [0,1] 범위로 변환
x_train = mnist.data[:60000]
x_test = mnist.data[60000:]
y_train = np.int16(mnist.target[:60000])
y_test = np.int16(mnist.target[60000:])

# MLP 분류기 모델을 학습
mlp = MLPClassifier(hidden_layer_sizes = (100), learning_rate_init = 0.001, batch_size = 512, max_iter = 300, solver = 'adam', verbose = True)
mlp.fit(x_train, y_train) # digit 데이터로 모델링 (모델 학습)

# 테스트 집합으로 예측
res = mlp.predict(x_test)  

# 혼동 행렬 
conf = np.zeros((10,10))

for i in range(len(res)):
  conf[res[i]][y_test[i]] += 1
print(conf)

# 정확률 계산
no_correct = 0
for i in range(10):
  no_correct += conf[i][i]
accuracy = no_correct/len(res)
print('\n테스트 집합에 대한 정확률은 ', accuracy*100,"%입니다.")

Iteration 1, loss = 0.60944217
Iteration 2, loss = 0.25730312
Iteration 3, loss = 0.20329726
Iteration 4, loss = 0.16910290
Iteration 5, loss = 0.14496842
Iteration 6, loss = 0.12753874
Iteration 7, loss = 0.11205003
Iteration 8, loss = 0.10050731
Iteration 9, loss = 0.09086324
Iteration 10, loss = 0.08287398
Iteration 11, loss = 0.07475398
Iteration 12, loss = 0.06930070
Iteration 13, loss = 0.06343666
Iteration 14, loss = 0.05829960
Iteration 15, loss = 0.05446004
Iteration 16, loss = 0.05000703
Iteration 17, loss = 0.04662390
Iteration 18, loss = 0.04316967
Iteration 19, loss = 0.04014949
Iteration 20, loss = 0.03738237
Iteration 21, loss = 0.03505576
Iteration 22, loss = 0.03232063
Iteration 23, loss = 0.03017817
Iteration 24, loss = 0.02778149
Iteration 25, loss = 0.02604714
Iteration 26, loss = 0.02457820
Iteration 27, loss = 0.02307881
Iteration 28, loss = 0.02184803
Iteration 29, loss = 0.01997990
Iteration 30, loss = 0.01841497
Iteration 31, loss = 0.01723460
Iteration 32, los

- MLPClassifier는 원래 23개의 매개변수를 가짐 
  - 따로 설정하지 않으면 기본값을 사용 
  - max_iter = 300으로 설정했는데 86에서 학습을 멈춤 
    - 기본 값중 tol = 0.0001과 n_iter_no_change = 10 때문에
    - 10번 동안 손실 함수 감소량이 0.0001 이하면 멈추라는 뜻 

- 하이퍼 매개변수 설정 가이드라인
  - 논문이나 공식 문서를 참고 
  - 라이브러리 함수가 제공하는 기본값 사용
  - 중요한 하이퍼 매개변수를 골라 최적화
